### ISSUE TITLE
Better description of how to use and/or simple examples needed

### ISSUE THREAD

**Issue by alecloudenback** [JuliaDiff/AbstractDifferentiation.jl#31] opened 2022-01-11 03:52 UTC
As a unfamiliar user, I am left confused on how to use this package without examples or more documentation.

> To use AbstractDifferentiation, first construct a backend instance `ab::AD.AbstractBackend` using your favorite differentiation package in Julia that supports AbstractDifferentiation.

How does one do this? Is my favorite differentiation package supposed to document this?

Also, some simple examples (ie basic polynomial functions, not complex ODEs) would help new users by to showing how to use this package.

**Comment by gdalle** [comment] 2022-03-26 07:23
I'm not an AbstractDifferentiation.jl contributor, but from what I understand, the library defines several backend objects that are made available if the corresponding package is loaded (thanks to the magic of [Requires.jl](https://github.com/JuliaPackaging/Requires.jl)).
Here's an example:

```julia
julia> using AbstractDifferentiation

julia> ab = AD.ZygoteBackend()
ERROR: UndefVarError: ZygoteBackend not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:35
 [2] top-level scope
   @ REPL[3]:1

julia> using Zygote

julia> ab = AD.ZygoteBackend()
AbstractDifferentiation.ReverseRuleConfigBackend{Zygote.ZygoteRuleConfig{Zygote.Context}}(Zygote.ZygoteRuleConfig{Zygote.Context}(Zygote.Context(nothing)))

julia> f(x) = log(sum(exp, x))
f (generic function with 1 method)

julia> AD.gradient(ab, f, rand(10))
([0.07163448353282538, 0.08520350535348796, 0.09675622487503996, 0.1522744408520505, 0.12174662595572318, 0.07996969757526722, 0.07832665607158593, 0.11001685581681672, 0.06691909637037166, 0.1371524135968315],)
```

From what I can tell, the following backends are defined by AbstractDifferentiation.jl:

- `AD.TrackerBackend()` for [Tracker.jl](https://github.com/FluxML/Tracker.jl)
- `AD.ReverseDiffBackend()` for [ReverseDiff.jl](https://github.com/JuliaDiff/ReverseDiff.jl)
- `AD.ForwardDiffBackend()` for [ForwardDiff.jl](https://github.com/JuliaDiff/ForwardDiff.jl)
- `AD.FiniteDifferencesBackend()` for [FiniteDifferences.jl](https://github.com/JuliaDiff/FiniteDifferences.jl)
- `AD.ZygoteBackend()` for [Zygote.jl](https://github.com/FluxML/Zygote.jl)
- `AD.ReverseRuleConfigBackend(ruleconfig)` for any [ChainRules.jl](https://github.com/JuliaDiff/ChainRules.jl)-compatible reverse mode backend (not really sure how this one works)

Maybe adding this small explanation to the README would be helpful? I got this from reading the [paper](https://arxiv.org/abs/2109.12449) and source code, but users shouldn't need to.

**Comment by gdalle** [comment] 2022-03-26 07:25
See  #10 for a more detailed answer by professionals ;)

**Comment by alecloudenback** [comment] 2022-03-26 16:15
For sure, that's a great addition!

**Comment by gdalle** [comment] 2023-10-05 08:12
I think the current dev docs solves this

Duplicate of #10 so closing this

**Closed by gdalle** 2023-10-05 08:12 UTC
Labels: documentation
